version: '3.9'
services:

  user-timeline-redis:
    image: redis
    hostname: user-timeline-redis
    restart: always
    command: redis-server /social-network-microservices/config/redis.conf
    volumes:
    - ../../DSB/socialNetwork/config:/social-network-microservices/config

networks:
  default:
    external: true
    name: social-network-overlay
